server:
  #port: 8083
  port: 0
spring:
  application:
    name: msvc-product
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/msvc-product
    username: salva
    password: Test123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/microservices-realm
          jwk-set-uri: http://localhost:8181/realms/microservices-realm/protocol/openid-connect/certs


eureka:
  client:
    jersey:
      enabled: false # 👈 Aquí desactivas el cliente de Jersey conflictivo
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org.springframework.security: TRACE


